# Generated by Django 6.0.1 on 2026-01-08 21:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_object_id', models.PositiveIntegerField()),
                ('direction', models.CharField(choices=[('lux_to_eng', 'Luxembourgish to English'), ('eng_to_lux', 'English to Luxembourgish')], default='lux_to_eng', max_length=20)),
                ('user_answer', models.CharField(max_length=500)),
                ('was_correct', models.BooleanField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('card_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review History',
                'verbose_name_plural': 'Review History',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cards_studied', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('total_incorrect', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_study_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Stats',
                'verbose_name_plural': 'User Stats',
            },
        ),
        migrations.CreateModel(
            name='CardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_object_id', models.PositiveIntegerField()),
                ('times_shown', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('times_incorrect', models.IntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval', models.IntegerField(default=0)),
                ('repetitions', models.IntegerField(default=0)),
                ('last_shown', models.DateTimeField(blank=True, null=True)),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card Progress',
                'verbose_name_plural': 'Card Progress',
                'unique_together': {('user', 'card_content_type', 'card_object_id')},
            },
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards_seen', models.IntegerField(default=0)),
                ('cards_mastered', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='cards.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic Progress',
                'verbose_name_plural': 'Topic Progress',
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
