# Generated by Django 6.0.1 on 2026-01-08 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1)),
                ('order', models.IntegerField(default=0, help_text='Order in curriculum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cards.topic')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PhraseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luxembourgish', models.CharField(max_length=500)),
                ('english', models.CharField(max_length=500)),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('register', models.CharField(blank=True, choices=[('neutral', 'Neutral'), ('formal', 'Formal'), ('informal', 'Informal')], default='neutral', max_length=10)),
                ('topics', models.ManyToManyField(blank=True, to='cards.topic')),
            ],
            options={
                'verbose_name': 'Phrase Card',
                'verbose_name_plural': 'Phrase Cards',
            },
        ),
        migrations.CreateModel(
            name='VocabularyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luxembourgish', models.CharField(max_length=500)),
                ('english', models.CharField(max_length=500)),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topics', models.ManyToManyField(blank=True, to='cards.topic')),
            ],
            options={
                'verbose_name': 'Vocabulary Card',
                'verbose_name_plural': 'Vocabulary Cards',
            },
        ),
    ]
